const screens = [
  {group:'Acesso',id:'login',title:'Entrar',icon:'↪',subtitle:'Identificação do estabelecimento',description:'O operador começa com CNPJ e senha. O contexto da concessionária e o estado de acesso ficam claros.',points:['Campos e rótulos diretos, com espaço para erro junto ao campo.','Erro de credenciais distinto de indisponibilidade da conexão.','A tela preserva os dados digitados ao mostrar um erro.']},
  {group:'Acesso',id:'login-error',title:'Erro de acesso',icon:'!',subtitle:'Recuperação sem perder o formulário',description:'Exemplo de feedback quando não foi possível autenticar. Nenhuma sessão real é criada.',points:['Mensagem específica e próxima ação explícita.','CNPJ preenchido permanece na tela.']},
  {group:'Operação',id:'orders',title:'Pedidos',icon:'▤',subtitle:'Fila de trabalho e busca',description:'A lista dá prioridade ao pedido que exige uma ação, mostrando valores e saldo de forma legível.',points:['Busca por nome, documento ou número do pedido.','Filtros com nomes completos e resultado visível.','Novo pedido em botão de texto, fácil de descobrir.']},
  {group:'Operação',id:'orders-empty',title:'Busca sem resultado',icon:'⌕',subtitle:'Vazio contextual',description:'Um resultado vazio explica por que a lista está vazia e como voltar aos pedidos.',points:['Ação para limpar filtros.','Sem parecer falha de sincronização.']},
  {group:'Operação',id:'orders-error',title:'Falha ao carregar',icon:'↻',subtitle:'Estado de rede',description:'A lista não usa números antigos como se fossem atuais quando o carregamento falha.',points:['Erro contextual e ação de tentar novamente.','Texto sem código técnico exposto ao operador.']},
  {group:'Operação',id:'detail',title:'Detalhe do pedido',icon:'▣',subtitle:'Saldo, histórico e próxima ação',description:'O detalhe distingue o que é pedido, o que já foi pago e o valor ainda pendente.',points:['Saldo em destaque antes de cobrar.','Dados de cliente e serviço em seções curtas.','Documentação e relatório separados da ação principal.']},
  {group:'Operação',id:'documents',title:'Documentação',icon:'▧',subtitle:'Fotos do pedido',description:'A documentação tem um caminho próprio para visualizar anexos e tentar o envio novamente.',points:['Estado de upload aparece no contexto da foto.','A foto não é presumida como enviada antes da confirmação.']},
  {group:'Operação',id:'report',title:'Relatório',icon:'▤',subtitle:'Resumo imprimível',description:'O relatório reúne cliente, serviço, itens e pagamentos para conferência antes de imprimir.',points:['Agrupamento consistente dos dados.','A ação Imprimir é explícita.']},
  {group:'Operação',id:'profile',title:'Perfil',icon:'◉',subtitle:'Empresa, operador e equipe',description:'Identificação operacional enxuta, com a ação de sair em posição clara.',points:['Empresa e operador identificados.','Equipe em lista simples e legível.']},
  {group:'Novo pedido',id:'new-order',title:'Dados do pedido',icon:'＋',subtitle:'Etapa 1 de 2',description:'O cadastro acompanha a ordem natural de atendimento: cliente, veículo e vendedor.',points:['Progresso textual e uma ação por etapa.','Validação no campo e preservação dos dados.','Campos com teclado e tamanho adequados à SmartPOS.']},
  {group:'Novo pedido',id:'order-review',title:'Revisar pedido',icon:'✓',subtitle:'Etapa 2 de 2',description:'A revisão dá ao operador uma última oportunidade de conferir dados e total antes de criar o pedido.',points:['Valor total isolado de outros números.','Criar pedido é diferente de cobrar.','Desconto aparece como item separado.']},
  {group:'Novo pedido',id:'order-created',title:'Pedido criado',icon:'●',subtitle:'Criação confirmada',description:'O resultado encerra a etapa de cadastro e oferece uma próxima ação compreensível.',points:['Confirmação inequívoca do pedido.','Atalho para abrir o detalhe e cobrar depois.']},
  {group:'Cobrança',id:'method',title:'Forma de pagamento',icon:'▱',subtitle:'Escolha do meio de pagamento',description:'A seleção mostra os meios como decisões comparáveis, com o saldo disponível acima.',points:['Métodos agrupados por função.','Parcelamento aparece somente após selecionar crédito.','Sem iniciar pagamento nesta tela.']},
  {group:'Cobrança',id:'amount',title:'Valor da cobrança',icon:'＄',subtitle:'Entrada com teclado grande',description:'O valor parte do saldo pendente e pode ser ajustado para um pagamento parcial.',points:['Limite do saldo sempre visível.','Aviso claro para zero ou valor superior ao saldo.']},
  {group:'Cobrança',id:'installments',title:'Parcelas',icon:'Ⅲ',subtitle:'Condições antes da confirmação',description:'As parcelas são escolhas explícitas. Os números do protótipo são apenas ilustrativos.',points:['Valor por parcela e total juntos.','Juros visíveis na escolha e no resumo final.']},
  {group:'Cobrança',id:'payment-review',title:'Revisão do pagamento',icon:'✓',subtitle:'Última conferência',description:'Método, valor original, juros e total ficam juntos antes de qualquer cobrança.',points:['Botão de confirmação com verbo e valor.','Resumo financeiro sem informações escondidas.','Confirmação em etapa própria.']},
  {group:'Cobrança',id:'processing',title:'Processando',icon:'◌',subtitle:'Operação em andamento',description:'O protótipo mostra a sequência de estados sem afirmar que uma transação real ocorreu.',points:['Orientação para manter o terminal disponível.','Nenhum incentivo a repetir a cobrança durante a espera.','Resultados de aprovação e falha acessíveis na demonstração.']},
  {group:'Cobrança',id:'approved',title:'Pagamento aprovado',icon:'✓',subtitle:'Resultado e comprovante',description:'Resultado de exemplo com valor, método e referência fictícia em um único lugar.',points:['Aprovação em texto e cor.','Comprovante consultável.','Voltar ao pedido como próximo passo.']},
  {group:'Cobrança',id:'failed',title:'Pagamento não concluído',icon:'!',subtitle:'Falha e recuperação',description:'O estado de falha separa tentativa de pagamento confirmado e orienta a conferência.',points:['Não declarar pagamento sem confirmação.','Voltar ao pedido e verificar status antes de repetir.']},
  {group:'Cobrança',id:'simulator',title:'Simular parcelas',icon:'≋',subtitle:'Consulta sem cobrar',description:'A simulação é identificada como consulta, fora da sequência de cobrança.',points:['Total e parcelas visíveis.','Os valores ilustrativos não são uma cotação do backend.']},
];

const byId = Object.fromEntries(screens.map(screen => [screen.id, screen]));
const state = {screen:'orders',history:[],filter:'Todos',query:'',selectedOrder:568,method:'Crédito',amountCents:153168,amountFresh:true,installments:3,simAmountCents:153168,customer:'Marina Costa',doc:'000.000.000-00',phone:'(11) 99999-0000',vehicle:'Automóvel',vehicleValue:'R$ 42.000,00',seller:'Ana Oliveira',discount:false,loginCnpj:'',loginPassword:'',photoStatus:'idle'};
const orders = [
  {id:568,name:'Marina Costa',date:'21 AGO',total:'R$ 2.531,68',paid:'R$ 1.000,00',due:'R$ 1.531,68',status:'Pendente'},
  {id:565,name:'Distribuidora Cidade Ltda.',date:'17 AGO',total:'R$ 1.252,12',paid:'R$ 0,00',due:'R$ 1.252,12',status:'Pendente'},
  {id:554,name:'Roberto Almeida',date:'13 AGO',total:'R$ 2.570,18',paid:'R$ 2.570,18',due:'R$ 0,00',status:'Quitado'}
];
const activeOrder = () => orders.find(order => order.id === state.selectedOrder) || orders[0];
const cents = value => Number(value.replace(/[^0-9]/g,''));
const pendingCents = () => cents(activeOrder().due);
const orderLabel = () => `Pedido #${activeOrder().id}`;
const app = document.getElementById('app');
const menu = document.getElementById('screen-menu');
const money = cents => (cents/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
const tag = (label,tone) => `<span class="tag ${tone}">${label}</span>`;
const head = (title,sub='',blue=false,back=true) => `<header class="app-head ${blue?'blue':''}"><div class="head-row">${back?'<button class="head-back" data-action="back" aria-label="Voltar">‹</button>':''}<h2>${title}</h2>${back?'<button class="icon-btn" data-action="orders" aria-label="Fechar e ir para pedidos">×</button>':''}</div>${sub?`<p class="head-sub">${sub}</p>`:''}</header>`;
const foot = (label,action,secondary='',secondaryAction='') => `<footer class="foot">${secondary?`<button class="btn outline" style="margin-bottom:8px" data-action="${secondaryAction}">${secondary}</button>`:''}<button class="btn primary" data-action="${action}">${label}</button></footer>`;
const nav = active => `<nav class="bottom-nav"><button data-action="orders" class="${active==='orders'?'active':''}"><span class="nav-icon">⌂</span>Pedidos</button><button data-action="simulator" class="${active==='simulator'?'active':''}"><span class="nav-icon">≋</span>Simular</button><button data-action="profile" class="${active==='profile'?'active':''}"><span class="nav-icon">◉</span>Perfil</button></nav>`;
const line = (label,value) => `<div class="info-line"><span>${label}</span><b>${value}</b></div>`;
const card = contents => `<div class="card">${contents}</div>`;
const progress = step => `<div class="progress"><span class="on"></span><span class="${step===2?'on':''}"></span></div>`;
const field = (label,id,value='',type='text',placeholder='') => `<label class="field"><span>${label}</span><input id="${id}" type="${type}" value="${escapeHtml(value)}" placeholder="${placeholder}" autocomplete="off"></label>`;
function renderMenu(){
  const groups=[...new Set(screens.map(s=>s.group))];
  menu.innerHTML=groups.map(group=>`<div class="menu-group"><small>${group.toUpperCase()}</small>${screens.filter(s=>s.group===group).map(s=>`<button data-screen="${s.id}" class="${state.screen===s.id?'active':''}"><span>${s.icon}</span>${s.title}</button>`).join('')}</div>`).join('');
}
function navigate(id,remember=true){if(!byId[id])return;if(remember&&state.screen!==id)state.history.push(state.screen);state.screen=id;render();}
function back(){const previous=state.history.pop();navigate(previous||'orders',false)}
function render(){
  const s=byId[state.screen];
  document.getElementById('stage-title').textContent=s.title;
  document.getElementById('stage-subtitle').textContent=s.subtitle;
  document.getElementById('inspector-title').textContent=s.title;
  document.getElementById('inspector-description').textContent=s.description;
  document.getElementById('inspector-points').innerHTML=s.points.map(p=>`<li>${p}</li>`).join('');
  renderMenu();app.innerHTML=views[state.screen]();app.querySelector('.content')?.scrollTo(0,0);
}

const views={
  'login':()=>`<div class="login-top"><div class="brand"><span class="brand-mark">D<span>·</span></span><strong>detrapay</strong></div><h2>Bem-vindo de volta</h2><p>Seu terminal pronto para atender com segurança.</p></div><div class="login-body"><h3>Entrar no terminal</h3><p>Use os dados do seu estabelecimento para continuar.</p>${field('CNPJ','login-cnpj',state.loginCnpj,'text','00.000.000/0000-00')}${field('Senha','login-password',state.loginPassword,'password','Sua senha')}<button class="btn primary" data-action="login-submit">Entrar</button><div class="alert blue" style="margin-top:22px">Confirme o estabelecimento antes de iniciar as cobranças.</div></div>`,
  'login-error':()=>`<div class="login-top"><div class="brand"><span class="brand-mark">D<span>·</span></span><strong>detrapay</strong></div><h2>Bem-vindo de volta</h2><p>Seu terminal pronto para atender com segurança.</p></div><div class="login-body"><h3>Entrar no terminal</h3><p>Confira os dados e tente novamente.</p>${field('CNPJ','login-cnpj',state.loginCnpj||'12.345.678/0001-90')}${field('Senha','login-password',state.loginPassword||'••••••••','password')}<div class="alert red"><strong>Não foi possível entrar.</strong><br>Verifique o CNPJ e a senha. Se o problema continuar, consulte o responsável pelo acesso.</div><button class="btn primary" data-action="login-submit">Tentar entrar novamente</button></div>`,
  'orders':()=>`<header class="app-head"><div class="head-row"><div style="flex:1"><span class="eyeline">BOM DIA, ANA</span><h2>Pedidos</h2></div><button class="icon-btn" data-action="profile" aria-label="Abrir perfil">◉</button></div><p class="head-sub">Auto Central · Terminal 04</p></header><div class="content"><div class="search">⌕ <input id="order-search" value="${escapeHtml(state.query)}" placeholder="Buscar nome, CPF/CNPJ ou pedido" aria-label="Buscar pedidos"></div><div class="filter-row">${['Todos','Pendentes','Quitados'].map(f=>`<button class="chip ${state.filter===f?'active':''}" data-filter="${f}">${f}</button>`).join('')}</div><div class="row" style="margin:17px 0 9px"><span class="eyeline">PEDIDOS RECENTES</span><button class="linkish" data-action="new-order">＋ Novo pedido</button></div><div id="order-list">${renderOrders()}</div><div class="alert blue">Os valores exibidos são dados fictícios para avaliação do protótipo.</div></div>${nav('orders')}`,
  'orders-empty':()=>`${head('Pedidos','Busca e acompanhamento',false,false)}<div class="content"><div class="search">⌕ <input value="XYZ-999" aria-label="Busca sem resultado"></div><div class="filter-row"><button class="chip active">Todos</button><button class="chip">Pendentes</button><button class="chip">Quitados</button></div><div class="center-state"><div class="state-icon blue">⌕</div><h3>Nenhum pedido encontrado</h3><p>Não há pedidos para “XYZ-999”. Tente outro nome, documento ou número.</p><button class="btn secondary" style="margin-top:22px" data-action="orders">Limpar busca</button></div></div>${nav('orders')}`,
  'orders-error':()=>`${head('Pedidos','Busca e acompanhamento',false,false)}<div class="content"><div class="center-state"><div class="state-icon red">!</div><h3>Pedidos indisponíveis</h3><p>Não foi possível carregar a lista agora. Confira a conexão do terminal e tente novamente.</p><button class="btn primary" style="margin-top:22px" data-action="orders">Tentar novamente</button></div></div>${nav('orders')}`,
  'detail':()=>`${head(orderLabel(),`Criado em ${activeOrder().date.toLowerCase()} · Vendedora Ana Oliveira`)}<div class="content"><div class="hero-card"><small>${pendingCents()>0?'SALDO PENDENTE':'PEDIDO QUITADO'}</small><div class="amount">${activeOrder().due}</div><div class="hero-foot"><span>Total ${activeOrder().total}</span><span>Pago ${activeOrder().paid}</span></div></div>${card(`<div class="row"><div><span class="eyeline">CLIENTE</span><div class="strong" style="margin-top:5px">${escapeHtml(activeOrder().name)}</div></div>${tag(activeOrder().status,activeOrder().status==='Quitado'?'green':'amber')}</div>${line('Documento','***.456.789-**')}${line('WhatsApp','(11) 99999-0000')}`)}${card(`<div class="section-title" style="margin-top:0">Pedido</div>${line('Serviço','Regularização veicular')}${line('Veículo','Automóvel')}${line('Vendedora','Ana Oliveira')}<div class="divider"></div><button class="linkish" data-action="report">Ver relatório completo →</button>`)}<div class="section-title">Pagamentos</div>${card(pendingCents()===cents(activeOrder().total)?'<p class="hint">Nenhum pagamento registrado para este pedido.</p>':`<div class="row"><div><b style="font-size:12px">Pagamento registrado</b><div class="hint">Consulte o relatório para os dados completos</div></div><b style="font-size:12px">${activeOrder().paid}</b></div>`)}<button class="btn outline" data-action="documents">▧ &nbsp; Ver documentação</button></div>${pendingCents()>0?foot(`Cobrar saldo de ${activeOrder().due}`,'method'):foot('Voltar aos pedidos','orders')}`,
  'documents':()=>`${head('Documentação',`${orderLabel()} · ${escapeHtml(activeOrder().name)}`)}<div class="content"><div class="section-title">Fotos do pedido</div><p class="hint">Confirme que cada foto foi enviada antes de sair desta tela.</p>${card(`<div class="photo-row"><div class="photo-box">▧<br>Frente</div><div class="photo-box">▧<br>Documento</div></div><div class="alert green">2 fotos de exemplo disponíveis para visualização.</div>`)}${state.photoStatus==='failed'?'<div class="alert red">O envio da nova foto não foi confirmado. Tente novamente ou descarte a foto pendente.</div>':''}<button class="btn outline" data-action="photo">▣ &nbsp; ${state.photoStatus==='failed'?'Tentar envio novamente':'Simular nova foto'}</button><p class="hint" style="margin-top:15px">Em produção, esta ação usa a câmera do terminal e aguarda confirmação do servidor.</p></div>${foot('Voltar ao pedido','detail')}`,
  'report':()=>`${head('Relatório do pedido',`${orderLabel()} · Prévia para impressão`)}<div class="content tight">${card(`<span class="eyeline">CLIENTE</span><h3 style="font-size:14px;margin:5px 0 8px">${escapeHtml(activeOrder().name)}</h3>${line('Documento','***.456.789-**')}${line('Telefone','(11) 99999-0000')}`)}${card(`<span class="eyeline">DADOS DO PEDIDO</span>${line('Serviço','Regularização veicular')}${line('Veículo','Automóvel')}${line('Vendedora','Ana Oliveira')}`)}${card(`<span class="eyeline">ITENS E PAGAMENTOS</span>${line('Serviços',activeOrder().total)}${line('Pago',activeOrder().paid)}<div class="divider"></div>${line('Saldo pendente',activeOrder().due)}`)}<p class="hint">Prévia de estrutura. A impressão real depende da integração com a impressora da SmartPOS.</p></div>${foot('Imprimir relatório · demonstração','print-demo')}`,
  'profile':()=>`${head('Perfil','Dados do estabelecimento',false,false)}<div class="content">${card(`<div class="row"><div class="profile-avatar">AC</div>${tag('Terminal 04','blue')}</div><h3 style="font-size:17px;margin:12px 0 3px">Auto Central</h3><div class="hint">CNPJ 12.345.678/0001-90</div><div class="divider"></div>${line('Operadora','Ana Oliveira')}${line('Função','Atendimento')}`)}<div class="section-title">Equipe</div>${card(`<div class="row"><div class="profile-avatar">AO</div><div style="flex:1"><b style="font-size:12px">Ana Oliveira</b><div class="hint">Vendedora</div></div></div>`)}${card(`<div class="row"><div class="profile-avatar">RP</div><div style="flex:1"><b style="font-size:12px">Rafael Pereira</b><div class="hint">Vendedor</div></div></div>`)}<button class="btn outline" data-action="login">Sair da conta</button></div>${nav('profile')}`,
  'new-order':()=>`${head('Novo pedido','Etapa 1 de 2 · Dados do cliente e veículo')}<div class="content">${progress(1)}<div class="step-copy">ETAPA 1 DE 2</div><h3 class="block-heading">Quem é o cliente?</h3><p class="hint">Confira os dados antes de avançar.</p>${field('CPF ou CNPJ','f-doc',state.doc,'text','000.000.000-00')}${field('Nome do cliente','f-name',state.customer,'text','Nome completo')}${field('WhatsApp','f-phone',state.phone,'tel','(00) 00000-0000')}<div class="section-title">Dados do veículo</div>${field('Valor do veículo','f-value',state.vehicleValue,'text','R$ 0,00')}<div class="field-grid">${field('Data de aquisição','f-date','22/09/2026','text','dd/mm/aaaa')}<label class="field"><span>Tipo de veículo</span><select id="f-vehicle"><option ${state.vehicle==='Automóvel'?'selected':''}>Automóvel</option><option>Motocicleta</option><option>Caminhão</option></select></label></div><label class="field"><span>Vendedor</span><select id="f-seller"><option>Ana Oliveira</option><option>Rafael Pereira</option></select></label><div class="checkbox-row"><input type="checkbox" id="f-financed"><label for="f-financed">Veículo com alienação</label></div><div class="checkbox-row"><input type="checkbox" id="f-plate"><label for="f-plate">Placa especial</label></div><div id="form-error"></div></div>${foot('Revisar pedido','review-order')}`,
  'order-review':()=>`${head('Revisar pedido','Etapa 2 de 2 · Confira antes de criar')}<div class="content">${progress(2)}<div class="step-copy">ETAPA 2 DE 2</div><h3 class="block-heading">Tudo certo para criar?</h3><p class="hint">Criar o pedido não inicia a cobrança.</p>${card(`<div class="row"><span class="eyeline">CLIENTE</span><button class="linkish" data-action="new-order">Editar</button></div><b style="display:block;margin-top:8px;font-size:13px">${escapeHtml(state.customer)}</b>${line('Documento',escapeHtml(state.doc))}${line('WhatsApp',escapeHtml(state.phone))}`)}${card(`<div class="row"><span class="eyeline">VEÍCULO E SERVIÇO</span><button class="linkish" data-action="new-order">Editar</button></div>${line('Tipo',escapeHtml(state.vehicle))}${line('Valor do veículo',escapeHtml(state.vehicleValue))}${line('Vendedor',escapeHtml(state.seller))}`)}${card(`<span class="eyeline">RESUMO FINANCEIRO · EXEMPLO</span>${line('Serviços','R$ 2.531,68')}${state.discount?line('Desconto','− R$ 100,00'):''}<div class="divider"></div><div class="row"><b>Total do pedido</b><span class="money">${state.discount?'R$ 2.431,68':'R$ 2.531,68'}</span></div>`)}<button class="btn outline" data-action="discount">${state.discount?'Remover desconto':'Adicionar desconto de exemplo'}</button><p class="hint">Os itens e valores são fictícios; o app real deve usar a simulação calculada pelo backend.</p></div>${foot('Criar pedido','create-order')}`,
  'order-created':()=>`${head('Pedido criado','Fluxo de cadastro concluído')}<div class="content"><div class="center-state"><div class="state-icon green">✓</div><h3>Pedido #569 criado</h3><p>O cadastro foi concluído. Você pode abrir o pedido para consultar os dados e iniciar a cobrança.</p></div><div class="receipt"><div class="rid">PEDIDO DE EXEMPLO</div><h3>#569 · ${escapeHtml(state.customer)}</h3>${line('Total',state.discount?'R$ 2.431,68':'R$ 2.531,68')}${line('Situação','Aguardando pagamento')}</div></div>${foot('Abrir pedido','detail','Voltar aos pedidos','orders')}`,
  'method':()=>`${head('Forma de pagamento',`${orderLabel()} · Saldo ${activeOrder().due}`)}<div class="content"><div class="step-copy">COBRANÇA · 1 DE 4</div><h3 class="block-heading">Como o cliente vai pagar?</h3><p class="hint">Escolha uma forma para continuar. A cobrança só ocorre após a revisão.</p><div class="section-title">Cartão</div>${method('Crédito','▭','Parcelamento disponível')}${method('Débito','▭','Pagamento à vista')}<div class="section-title">Outras formas</div>${method('Pix','◇','Pagamento instantâneo')}${method('Dinheiro','＄','Registrar recebimento')}${method('Crédito loja','▣','Registrar crédito da loja')}<div class="alert blue">Disponibilidade e regras de cada método vêm do app e dos dados do estabelecimento.</div></div>`,
  'amount':()=>`${head('Valor da cobrança',`${orderLabel()} · ${escapeHtml(state.method)}`)}<div class="content"><div class="step-copy">COBRANÇA · 2 DE 4</div><div class="key-amount"><small>Quanto deseja cobrar?</small><strong>${money(state.amountCents)}</strong></div><div class="total-bar"><div class="row"><span>Saldo disponível</span><b>${activeOrder().due}</b></div><button class="linkish" style="margin-top:7px" data-action="use-balance">Usar saldo total</button></div><div id="amount-error"></div><div class="keypad">${['1','2','3','4','5','6','7','8','9',',','0','⌫'].map(key=>`<button data-key="${key}" aria-label="${key==='⌫'?'Apagar':key}">${key}</button>`).join('')}</div><p class="hint" style="text-align:center">Ao digitar, o primeiro número substitui o valor sugerido. O restante continua no pedido.</p></div>${foot(state.method==='Crédito'?'Ver parcelas':'Revisar pagamento','amount-next')}`,
  'installments':()=>`${head('Parcelamento','Crédito · Valor base ${money(state.amountCents)}')}<div class="content"><div class="step-copy">COBRANÇA · 3 DE 4</div><h3 class="block-heading">Escolha as parcelas</h3><p class="hint">Confira o valor de cada parcela e o total que será cobrado.</p><div class="alert amber">Valores ilustrativos. Em produção, as opções e taxas devem vir da consulta real.</div>${[1,2,3,6].map(n=>{const total=quote(n),each=money(Math.round(total/n));return `<div class="card option ${state.installments===n?'selected':''} pressable" data-installments="${n}"><span class="radio"></span><div style="flex:1"><div class="label">${n===1?'À vista':`${n}x de ${each}`}</div><small>${n===1?'Sem juros neste exemplo':`Juros de ${money(total-state.amountCents)}`}</small></div><b style="font-size:11px">${money(total)}</b></div>`}).join('')}<div class="total-bar"><div class="row"><span>Total selecionado</span><b>${money(quote(state.installments))}</b></div></div></div>${foot('Revisar pagamento','payment-review')}`,
  'payment-review':()=>`${head('Revisar pagamento',`${orderLabel()} · Última conferência`)}<div class="content"><div class="step-copy">COBRANÇA · 4 DE 4</div><h3 class="block-heading">Confirme os dados</h3><p class="hint">Peça ao cliente para conferir método, parcelas e total.</p>${card(`<div class="row"><div class="method-icon">▭</div><div style="flex:1"><b style="font-size:13px">${escapeHtml(state.method)}</b><div class="hint">${state.method==='Crédito'?`${state.installments}x no cartão`:'Pagamento à vista'}</div></div>${tag('A confirmar','blue')}</div><div class="divider"></div>${line('Valor original',money(state.amountCents))}${line('Taxas e juros',money(quote(state.installments)-state.amountCents))}${state.method==='Crédito'?line('Parcelamento',`${state.installments}x de ${money(Math.round(quote(state.installments)/state.installments))}`):''}<div class="divider"></div><div class="row"><b>TOTAL A COBRAR</b><span class="money">${money(quote(state.installments))}</span></div>`)}<div class="alert amber">Após confirmar, aguarde o resultado da operação no terminal. Evite iniciar outra cobrança enquanto esta estiver em andamento.</div></div>${foot(`Confirmar cobrança de ${money(quote(state.installments))}`,'processing','Alterar forma de pagamento','method')}`,
  'processing':()=>`${head('Pagamento em andamento',`${orderLabel()} · Não repita a cobrança`)}<div class="content"><div class="spinner"></div><div class="center-state" style="padding-top:0"><h3>Aguarde o terminal</h3><p>Estamos aguardando o resultado da operação. Mantenha o terminal disponível para o cliente.</p></div><div class="card timeline"><div class="event"><i>✓</i><span>Dados revisados</span></div><div class="event"><i>✓</i><span>Operação iniciada no protótipo</span></div><div class="event pending"><i>…</i><span>Resultado aguardando confirmação</span></div></div><div class="alert blue">Demonstração: selecione abaixo qual resultado deseja visualizar. Nenhuma transação foi enviada.</div><div class="stack"><button class="btn secondary" data-action="approved">Ver exemplo de aprovação</button><button class="btn outline" data-action="failed">Ver exemplo de falha</button></div></div>`,
  'approved':()=>`${head('Resultado','Pagamento concluído')}<div class="content"><div class="center-state"><div class="state-icon green">✓</div><h3>Pagamento aprovado</h3><p>Exemplo de resultado confirmado. Em produção, esta tela só deve aparecer após confirmação da operação.</p></div><div class="receipt"><div class="rid">COMPROVANTE ILUSTRATIVO</div><h3>${orderLabel()}</h3>${line('Valor total',money(quote(state.installments)))}${line('Forma de pagamento',escapeHtml(state.method))}${state.method==='Crédito'?line('Parcelas',`${state.installments}x`):''}${line('Referência','DEMO-2026-001')}${line('Situação','Aprovado')}</div></div>${foot('Voltar ao pedido','detail')}`,
  'failed':()=>`${head('Resultado','Pagamento não concluído')}<div class="content"><div class="center-state"><div class="state-icon red">!</div><h3>Não houve confirmação</h3><p>Esta tentativa não foi concluída no exemplo. Consulte a situação do pedido antes de iniciar outra cobrança.</p></div><div class="alert red"><strong>O saldo continua pendente.</strong><br>Uma nova tentativa só deve começar depois de verificar o resultado da anterior.</div>${card(`${line('Pedido',`#${activeOrder().id}`)}${line('Valor tentado',money(quote(state.installments)))}${line('Método',escapeHtml(state.method))}`)}</div>${foot('Verificar pedido','detail','Voltar aos pedidos','orders')}`,
  'simulator':()=>`${head('Simular parcelas','Consulta sem cobrança',false,false)}<div class="content"><div class="step-copy">SIMULAÇÃO</div><h3 class="block-heading">Quanto fica parcelado?</h3><p class="hint">Esta consulta não inicia nem registra um pagamento.</p>${field('Valor para simular','sim-amount',money(state.simAmountCents),'text','R$ 0,00')}<button class="btn secondary" data-action="simulate">Consultar parcelas</button><div class="alert amber">Taxas e resultados abaixo são ilustrativos. A simulação real depende da consulta ao backend.</div><div class="section-title">Resultado de exemplo</div>${[1,2,3,6].map(n=>`<div class="card option"><div class="method-icon">${n}x</div><div style="flex:1"><b style="font-size:12px">${n===1?'À vista':`${n} parcelas`}</b><div class="hint">${money(Math.round(simQuote(n)/n))} por parcela</div></div><b style="font-size:12px">${money(simQuote(n))}</b></div>`).join('')}</div>${nav('simulator')}`
};
function method(name,icon,subtitle){return `<div class="card method-item pressable" data-method="${name}"><span class="method-icon">${icon}</span><div><div class="name">${name}</div><small>${subtitle}</small></div><span class="chevron">›</span></div>`}
function quote(n){return state.method==='Crédito'&&n>1?Math.round(state.amountCents*(1+({2:.02,3:.035,6:.075}[n]||0))/n)*n:state.amountCents}
function simQuote(n){return n>1?Math.round(state.simAmountCents*(1+({2:.02,3:.035,6:.075}[n]||0))/n)*n:state.simAmountCents}
function renderOrders(){const query=state.query.toLocaleLowerCase('pt-BR').trim();const filtered=orders.filter(o=>(state.filter==='Todos'||(state.filter==='Pendentes'&&o.status==='Pendente')||(state.filter==='Quitados'&&o.status==='Quitado'))&&(!query||`${o.id} ${o.name}`.toLocaleLowerCase('pt-BR').includes(query)));return filtered.length?filtered.map(o=>`<article class="card order-card pressable" data-action="open-order" data-order="${o.id}"><div class="row order-top"><span><strong>#${o.id}</strong> · ${o.date}</span>${tag(o.status,o.status==='Quitado'?'green':'amber')}</div><div class="customer">${escapeHtml(o.name)}</div><div class="triple"><div><small>TOTAL</small><b>${o.total}</b></div><div><small>PAGO</small><b>${o.paid}</b></div><div><small>FALTA</small><b class="${o.status==='Pendente'?'red':''}">${o.due}</b></div></div></article>`).join(''):`<div class="center-state"><div class="state-icon blue">⌕</div><h3>Nenhum pedido encontrado</h3><p>Experimente outro termo ou limpe os filtros.</p><button class="btn secondary" data-action="clear-search" style="margin-top:18px">Limpar busca</button></div>`}

menu.addEventListener('click',event=>{const button=event.target.closest('[data-screen]');if(button)navigate(button.dataset.screen)});
app.addEventListener('click',event=>{
  const methodButton=event.target.closest('[data-method]');if(methodButton){state.method=methodButton.dataset.method;state.installments=state.method==='Crédito'?3:1;state.amountCents=pendingCents();state.amountFresh=true;navigate('amount');return}
  const installmentButton=event.target.closest('[data-installments]');if(installmentButton){state.installments=Number(installmentButton.dataset.installments);render();return}
  const filterButton=event.target.closest('[data-filter]');if(filterButton){state.filter=filterButton.dataset.filter;render();return}
  const keyButton=event.target.closest('[data-key]');if(keyButton){const key=keyButton.dataset.key;if(key==='⌫'){state.amountCents=state.amountFresh?0:Math.floor(state.amountCents/10);state.amountFresh=false}else if(key!==','){state.amountCents=Math.min(99999999,Number(`${state.amountFresh?0:state.amountCents}${key}`));state.amountFresh=false}render();return}
  const button=event.target.closest('[data-action]');if(!button)return;const action=button.dataset.action;
  if(action==='back'){back();return}
  if(action==='login-submit'){state.loginCnpj=document.getElementById('login-cnpj')?.value||'';state.loginPassword=document.getElementById('login-password')?.value||'';navigate(state.loginCnpj&&state.loginPassword?'orders':'login-error');return}
  if(action==='review-order'){
    for(const [key,id] of [['doc','f-doc'],['customer','f-name'],['phone','f-phone'],['vehicleValue','f-value'],['vehicle','f-vehicle'],['seller','f-seller']])state[key]=document.getElementById(id)?.value||'';
    if(!state.doc||!state.customer||!state.phone||!state.vehicleValue){document.getElementById('form-error').innerHTML='<div class="alert red">Preencha documento, nome, WhatsApp e valor do veículo para continuar.</div>';return}navigate('order-review');return;
  }
  if(action==='discount'){state.discount=!state.discount;render();return}
  if(action==='create-order'){const total=state.discount?'R$ 2.431,68':'R$ 2.531,68';const created={id:569,name:state.customer,date:'22 SET',total,paid:'R$ 0,00',due:total,status:'Pendente'};const existing=orders.findIndex(order=>order.id===569);if(existing>=0)orders.splice(existing,1);orders.unshift(created);state.selectedOrder=569;navigate('order-created');return}
  if(action==='open-order'){state.selectedOrder=Number(button.dataset.order);state.amountCents=pendingCents();state.amountFresh=true;navigate('detail');return}
  if(action==='use-balance'){state.amountCents=pendingCents();state.amountFresh=true;render();return}
  if(action==='amount-next'){if(state.amountCents<1||state.amountCents>pendingCents()){document.getElementById('amount-error').innerHTML=`<div class="alert red">Informe um valor maior que zero e até ${activeOrder().due}.</div>`;return}navigate(state.method==='Crédito'?'installments':'payment-review');return}
  if(action==='photo'){state.photoStatus='failed';render();return}
  if(action==='print-demo'){alert('Prévia apenas. Nenhum comando foi enviado à impressora.');return}
  if(action==='simulate'){const raw=document.getElementById('sim-amount')?.value||'';const parts=raw.replace(/[^0-9,]/g,'').split(',');state.simAmountCents=parts.length>1?Number(parts[0].replace(/\D/g,''))*100+Number((parts[1]||'').padEnd(2,'0').slice(0,2)):Number(raw.replace(/\D/g,''))*100;if(!Number.isFinite(state.simAmountCents)||state.simAmountCents<1)state.simAmountCents=153168;render();return}
  if(action==='clear-search'){state.query='';state.filter='Todos';navigate('orders',false);return}
  navigate(action)
});
app.addEventListener('input',event=>{if(event.target.id==='order-search'){state.query=event.target.value;document.getElementById('order-list').innerHTML=renderOrders()}});
document.getElementById('reset-demo').addEventListener('click',()=>{state.history=[];state.filter='Todos';state.query='';state.selectedOrder=568;state.method='Crédito';state.amountCents=153168;state.amountFresh=true;state.simAmountCents=153168;state.installments=3;state.discount=false;const created=orders.findIndex(order=>order.id===569);if(created>=0)orders.splice(created,1);navigate('orders',false)});
render();
