(() => {
  'use strict';

  const initialOrders = () => [
    { id: 589, name: 'Marina Albuquerque', date: '23 set.', total: 123608, paid: 0, photos: 0 },
    { id: 588, name: 'Carlos Henrique Souza', date: '23 set.', total: 192068, paid: 40000, photos: 1 },
    { id: 568, name: 'Ana Larissa Ferreira', date: '21 ago.', total: 153168, paid: 153168, photos: 2 },
    { id: 561, name: 'João Victor Lima', date: '20 ago.', total: 899000, paid: 120000, photos: 0 },
    { id: 550, name: 'Patrícia Costa', date: '18 ago.', total: 89500, paid: 0, photos: 1 },
  ];
  const fresh = () => ({screen:'orders',orders:initialOrders(),selected:589,search:'',showSearch:false,detailDocumentsOpen:false,method:'credito',digits:'',installments:1,result:null,draft:{document:'',name:'',phone:'',vehicle:'',date:''},simDigits:'',toast:null});
  let s=fresh();
  const app=document.getElementById('app');
  const fmt=cents => (Math.max(0,cents)/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const order=()=>s.orders.find(o=>o.id===s.selected)||s.orders[0];
  const balance=o=>Math.max(0,o.total-o.paid);
  const amount=()=>Number(s.digits||0);
  const methodLabel=()=>({credito:'Crédito',debito:'Débito',pix:'Pix',dinheiro:'Dinheiro',pix_manual:'Pix recebido',store_credit:'Crédito da loja'}[s.method]||'Crédito');
  const isManual=()=>['dinheiro','pix_manual','store_credit'].includes(s.method);
  const fee=()=>s.method==='credito'&&s.installments>1?Math.round(amount()*0.029):0;
  const finalAmount=()=>amount()+fee();
  const paths={back:'M15 18l-6-6 6-6M9 12h12',search:'M11 19a8 8 0 1 0 0-16 8 8 0 0 0 0 16Zm6-2 4 4',person:'M20 21a8 8 0 0 0-16 0m8-10a4 4 0 1 0 0-8 4 4 0 0 0 0 8',close:'M18 6 6 18M6 6l12 12',plus:'M12 5v14M5 12h14',chev:'m9 18 6-6-6-6',camera:'M3 7h4l2-3h6l2 3h4v13H3V7Zm9 10a4 4 0 1 0 0-8 4 4 0 0 0 0 8Z',card:'M3 6h18v12H3V6Zm0 4h18',receipt:'M5 3h14v18l-3-2-4 2-4-2-3 2V3Zm3 5h8M8 12h8',check:'m4 12 5 5L20 6',warning:'M12 3 2 21h20L12 3Zm0 7v4m0 3h.01',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18Zm0 4v5l3 2',logout:'M9 4H4v16h5m4-4 4-4-4-4m4 4H8',bolt:'m13 2-9 11h7l-1 9 10-12h-7V2Z',copy:'M8 7h12v14H8V7ZM4 3h12v3',calendar:'M4 6h16v15H4V6Zm4-3v6m8-6v6M4 11h16'};
  const icon=(name)=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.chev}"/></svg>`;
  const ib=(name,action,label,soft=false)=>`<button type="button" class="icon-button ${soft?'soft':''}" data-action="${action}" aria-label="${label}">${icon(name)}</button>`;
  const header=(title,opts={})=>{
    let progress='';
    const paymentStep={methods:1,amount:2,installments:3,review:s.method==='credito'?4:3};
    if(paymentStep[s.screen]){
      const current=paymentStep[s.screen];
      const total=s.method==='credito'||s.screen==='methods'?4:3;
      progress=`<div class="flow-progress" role="progressbar" aria-label="Progresso do pagamento" aria-valuemin="0" aria-valuemax="${total}" aria-valuenow="${current}"><div class="flow-progress-label"><span>ETAPA ${current} DE ${total}</span><span>${Math.round(current/total*100)}%</span></div><div class="flow-progress-track"><i style="width:${current/total*100}%"></i></div></div>`;
    }else if(opts.step){
      const current=opts.step===50?1:2;
      progress=`<div class="flow-progress" role="progressbar" aria-label="Progresso do cadastro" aria-valuemin="0" aria-valuemax="2" aria-valuenow="${current}"><div class="flow-progress-label"><span>ETAPA ${current} DE 2</span><span>${opts.step}%</span></div><div class="flow-progress-track"><i style="width:${opts.step}%"></i></div></div>`;
    }else if(s.screen==='processing'){
      progress='<div class="flow-progress" role="progressbar" aria-label="Aguardando resultado do terminal" aria-valuetext="Em andamento"><div class="flow-progress-label"><span>AGUARDANDO TERMINAL</span><span>EM ANDAMENTO</span></div><div class="flow-progress-track busy"><i></i></div></div>';
    }
    return `<header class="screen-head"><div class="head-row">${opts.back?ib('back','back','Voltar'):''}<div class="grow"><h2>${title}</h2>${opts.subtitle?`<span class="subhead">${opts.subtitle}</span>`:''}</div>${opts.action||''}</div></header>${progress}`;
  };
  const main=(content,extra='')=>`<div class="screen-main ${extra}">${content}</div>`;
  const footer=(label,action,disabled=false,secondary='')=>`<footer class="screen-footer">${secondary?`<button type="button" class="minor" data-action="${secondary}">Voltar</button>`:''}<button type="button" class="primary" data-action="${action}" ${disabled?'disabled':''}>${label}</button></footer>`;
  const nav=active=>`<nav class="bottom-nav" aria-label="Navegação principal"><button data-action="orders" class="${active==='orders'?'active':''}"><span>▤</span>Pedidos</button><button data-action="new-order" class="${active==='new-order'?'active':''}"><span>＋</span>Novo pedido</button><button data-action="simulator" class="${active==='simulator'?'active':''}"><span>◈</span>Simular</button><button data-action="profile" class="${active==='profile'?'active':''}"><span>○</span>Perfil</button></nav>`;
  const chip=o=>balance(o)===0?'<span class="chip paid">CONCLUÍDO</span>':o.paid>0?'<span class="chip partial">EM PROGRESSO</span>':'<span class="chip pending">PENDENTE</span>';
  const screenInfo={
    login:['Acesso','Login mais direto','Marca, campos e ação principal ficam na primeira dobra. O erro mantém o que foi digitado.','Use qualquer CNPJ e senha para entrar na demonstração.'],
    orders:['Pedidos','Cartões preservados','Os cartões mantêm número, data, situação, cliente, pagamento e três métricas na disposição atual. A proposta ajusta a fonte e apresenta todo o texto dos cartões em caixa alta.','Abra a busca pelo ícone ou toque em um cartão.'],
    detail:['Pedido','Detalhe fiel ao app','A tela mantém cabeçalho, cartão de valor total, pagamentos, documentação e botão fixo. Os ajustes ficam na tipografia, nos espaçamentos e na leitura dos valores.','Visualize as fotos sob demanda ou toque em Receber pagamento.'],
    methods:['Pagamento','Meios separados por efeito','Cobranças na maquininha ficam separadas de registros manuais, evitando a impressão de que ambos têm a mesma confirmação.','Selecione Crédito, Débito, Pix ou um registro manual.'],
    amount:['Valor','Teclado próprio para o terminal','O valor fica grande, o saldo tem atalho e as teclas mantêm área de toque confortável na tela do GPOS780.','Digite um valor ou use o saldo; tente também ultrapassar o saldo.'],
    installments:['Parcelas','Condição inteira na escolha','Cada opção mostra parcela e total. A simulação de taxa é fictícia e a revisão repete todos os valores.','Selecione uma condição e avance.'],
    review:['Revisão','Antes da ação no terminal','Pedido, método, valor original, acréscimo e total aparecem juntos; o botão nomeia a ação que vem a seguir.','Confirme para ver a etapa simulada de processamento.'],
    processing:['Processamento','Resultado externo explícito','Enquanto o terminal decide, a tela não diz que houve aprovação. O resultado é controlado apenas pelo painel de demonstração.','Use os controles fora da tela para simular os três resultados.'],
    result:['Resultado','Estado e próxima ação claros','Aprovado, recusado e sem confirmação têm mensagens e opções diferentes; somente aprovação simulada altera o saldo local.','Volte ao pedido ou inicie outra simulação.'],
    'new-order':['Cadastro','Etapas com rascunho preservado','Os campos essenciais vêm primeiro e a revisão antecede a criação fictícia do pedido. Voltar mantém os dados.','Preencha cliente e valor do veículo para revisar.'],
    'new-review':['Cadastro','Revisão antes de criar','O resumo separa dados do cliente e do veículo, com volta segura ao formulário.','Crie um pedido fictício e abra seus detalhes.'],
    simulator:['Simulador','Sem confundir com cobrança','Uma área própria para simular parcelas; nada aqui inicia pagamento ou altera o pedido.','Digite um valor e veja as opções.'],
    profile:['Perfil','Informação operacional reunida','Operador, empresa e equipe aparecem em uma tela de consulta compacta.','Use a navegação inferior para voltar.'],
  };
  const views={
    login:()=>`<div class="login-hero"><strong>DETRAPAY</strong><p>Seu atendimento começa aqui.</p></div>${main(`<div class="login-form"><h2>Acessar terminal</h2><p>Entre com os dados da concessionária para continuar.</p>${field('CNPJ','login-document',s.loginDocument||'','00.000.000/0000-00')}${field('Senha','login-password',s.loginPassword||'','Sua senha','password')}<div class="alert blue">Demonstração: os dados não são enviados.</div><button class="primary" data-action="login-submit">Entrar</button></div>`)}`,
    orders:()=>`${header('Pedidos',{action:`${ib('search','toggle-search','Buscar pedidos',true)}${ib('person','profile','Abrir perfil')}`})}${main(`${s.showSearch?`<div class="searchbox"><span class="mini-icon">${icon('search')}</span><input id="search" data-field="search" value="${esc(s.search)}" placeholder="Buscar por cliente ou pedido" aria-label="Buscar por cliente ou pedido"></div>`:''}<div id="order-list"></div>`)}${footer('＋  Novo pedido','new-order')}`,
    detail:()=>{
      const o=order();
      const status=balance(o)===0?'CONCLUÍDO':o.paid>0?'EM PROGRESSO':'PENDENTE';
      return `${header(`Pedido #${o.id}`,{back:true,action:`<span class="detail-status">${icon('receipt')}${status}</span>`})}${main(`<section class="card detail-card detail-total"><div class="detail-total-heading"><div class="detail-dollar">$</div><div class="detail-total-value"><span>VALOR TOTAL DO PEDIDO</span><strong class="money">${fmt(o.total)}</strong></div>${ib('copy','copy-total','Copiar valor')}</div><div class="detail-rule"></div><div class="detail-total-metrics"><div><span class="detail-metric-label"><b class="received-arrow">↗</b> RECEBIDO</span><strong class="money">${fmt(o.paid)}</strong></div><div><span class="detail-metric-label"><b class="missing-arrow">↘</b> FALTA</span><strong class="money ${balance(o)>0?'missing':''}">${fmt(balance(o))}</strong></div></div></section><section class="card detail-card detail-payments"><h3>Pagamentos</h3>${o.paid?`<div class="detail-payment-item"><span class="detail-dollar small">▣</span><div><strong>PAGAMENTO REGISTRADO</strong><small>Valor recebido até agora</small></div><strong class="money">${fmt(o.paid)}</strong></div>`:'<p>Nenhum pagamento registrado.</p>'}</section><section class="card detail-card detail-docs"><div class="detail-docs-head"><div><h3>Documentação</h3><small>Fotos anexadas ao pedido</small></div><button type="button" class="detail-photo-button" data-action="take-photo">${icon('camera')} Tirar foto</button></div>${s.detailDocumentsOpen?`<div class="detail-photos-loaded">${o.photos?`<div class="photo-placeholder">${o.photos} foto${o.photos===1?'':'s'} fictícia${o.photos===1?'':'s'}</div>`:'Nenhuma foto anexada. Use a câmera para registrar o pedido.'}</div>`:`<p>As fotos não são carregadas automaticamente.</p><button type="button" class="detail-photo-link" data-action="view-photos">▣ &nbsp; Visualizar fotos</button>`}<div class="detail-docs-note">Formato JPEG. Tamanho máximo: 10 MB.</div></section>`,'detail-main')}${balance(o)>0?footer('Receber pagamento','pay'):''}`;
    },
    methods:()=>`${header('Receber pagamento',{back:true,subtitle:`Pedido #${order().id}`})}${main(`<div class="alert blue"><strong>Saldo disponível:</strong> ${fmt(balance(order()))}</div><div class="tiny-label" style="margin:14px 0 8px">NA MAQUININHA</div>${paymentOption('credito','▣','Crédito','À vista ou parcelado')}${paymentOption('debito','▣','Débito','Cartão no terminal')}${paymentOption('pix','◇','Pix','Gerado pela maquininha')}<div class="tiny-label" style="margin:18px 0 8px">REGISTRAR VALOR JÁ RECEBIDO</div>${paymentOption('dinheiro','$','Dinheiro','Registro manual')}${paymentOption('pix_manual','◇','Pix recebido','Transferência já confirmada fora do app')}${paymentOption('store_credit','▤','Crédito da loja','Valor concedido ao cliente')}`)}`,
    amount:()=>`${header('Valor do pagamento',{back:true,subtitle:`Pedido #${order().id} · ${methodLabel()}`})}<div class="keypad-layout"><div class="amount-hero"><span class="tiny-label">VALOR A RECEBER</span><strong id="amount-display" class="money">${fmt(amount())}</strong><button class="balance-pill" data-action="fill-balance">Usar saldo de ${fmt(balance(order()))}</button><div id="amount-error" class="caption" style="color:var(--red);min-height:16px;margin-top:7px"></div></div><div class="keypad">${['1','2','3','4','5','6','7','8','9','Limpar','0','⌫'].map(k=>`<button type="button" class="${['Limpar','⌫'].includes(k)?'action':''}" data-key="${esc(k)}">${k}</button>`).join('')}</div></div>${footer('Continuar','amount-next',amount()<=0)}`,
    installments:()=>`${header('Escolha as parcelas',{back:true,subtitle:`Crédito · ${fmt(amount())}`})}${main(`<div class="alert blue">Simulação de condições para demonstração. A taxa real deve vir do serviço de parcelas.</div>${[1,2,3,4,6].map(n=>{const total=amount()+(n>1?Math.round(amount()*.029):0);return `<button class="payment-option" data-installments="${n}" style="border-color:${s.installments===n?'#408ad0':''}"><span class="circle-icon">${n}×</span><span class="grow"><strong>${n} × ${fmt(Math.round(total/n))}</strong><small>Total ${fmt(total)}${n>1?' · inclui acréscimo':''}</small></span><span class="chev">${s.installments===n?'●':'○'}</span></button>`}).join('')}`)}${footer('Revisar pagamento','review')}`,
    review:()=>`${header('Revisar pagamento',{back:true,subtitle:`Pedido #${order().id}`})}${main(`<div class="alert ${isManual()?'amber':'blue'}">${isManual()?'Este método registra um valor informado pelo operador. Confirme que ele já foi recebido.':'Após confirmar, a operação será iniciada no terminal.'}</div><div class="card"><span class="tiny-label">CLIENTE</span><div class="strong" style="margin:5px 0 16px">${esc(order().name)}</div><div class="info-list"><div class="row spread"><span class="muted">Método</span><strong>${methodLabel()}</strong></div><div class="row spread"><span class="muted">Valor informado</span><strong>${fmt(amount())}</strong></div>${fee()?`<div class="row spread"><span class="muted">Acréscimo simulado</span><strong>${fmt(fee())}</strong></div>`:''}${s.method==='credito'?`<div class="row spread"><span class="muted">Parcelas</span><strong>${s.installments}×</strong></div>`:''}</div><hr class="divider"><div class="row spread"><strong>Total</strong><strong class="large money">${fmt(finalAmount())}</strong></div></div><p class="hint">Saldo atual do pedido: ${fmt(balance(order()))}. Nenhuma cobrança é realizada por este protótipo.</p>`)}${footer(isManual()?'Registrar valor fictício':'Iniciar no terminal','confirm')}`,
    processing:()=>`${header('Aguardando terminal',{back:true,subtitle:`Pedido #${order().id}`})}${main(`<div class="result-hero"><div class="loader" aria-hidden="true"></div><h3>Operação em andamento</h3><p>Oriente o cliente a aproximar ou inserir o cartão. A confirmação ainda não foi recebida.</p><span class="large money">${fmt(finalAmount())}</span><div class="alert blue">Aguarde uma resposta do terminal antes de registrar o resultado.</div></div>`)}${footer('Voltar ao pedido','detail')}`,
    result:()=>{const success=s.result==='approved',declined=s.result==='declined',manual=success&&isManual();return `${header('Resultado',{back:true,subtitle:`Pedido #${order().id}`})}${main(`<div class="result-hero"><div class="result-icon ${success?'green':declined?'red':'amber'}">${success?'✓':declined?'×':'?'}</div><h3>${manual?'Valor registrado':success?'Pagamento aprovado':declined?'Pagamento recusado':'Sem confirmação'}</h3><p>${manual?'O registro manual foi simulado. O saldo fictício do pedido foi atualizado.':success?'A aprovação foi simulada. O saldo fictício do pedido foi atualizado.':declined?'Nenhum valor foi registrado no pedido. Você pode tentar novamente.':'O resultado não foi confirmado. Confira o terminal antes de iniciar outra tentativa.'}</p><span class="large money">${fmt(finalAmount())}</span><div class="alert ${success?'green':declined?'red':'amber'}">${success?'Pedido atualizado apenas nesta demonstração.':declined?'Saldo do pedido preservado.':'Saldo preservado até existir confirmação.'}</div></div>`)}${footer(success?'Ver pedido':declined?'Tentar novamente':'Ver pedido',declined?'methods':'detail')}`},
    'new-order':()=>`${header('Novo pedido',{back:true,subtitle:'Etapa 1 de 2',step:50})}${main(`<div class="alert blue">O rascunho permanece ao voltar entre as etapas.</div><div class="form-group">Cliente</div>${field('CPF/CNPJ','document',s.draft.document,'Documento')}${field('Nome do cliente','name',s.draft.name,'Nome completo')}${field('WhatsApp','phone',s.draft.phone,'(00) 00000-0000')}<div class="form-group">Veículo</div>${field('Valor do veículo','vehicle',s.draft.vehicle,'R$ 0,00','text')}${field('Data de aquisição','date',s.draft.date,'dd/mm/aaaa')}<p class="hint">Dados adicionais e serviços podem ser conferidos antes de criar o pedido.</p>`,'with-footer')}${footer('Revisar pedido','new-review')}`,
    'new-review':()=>`${header('Revise o pedido',{back:true,subtitle:'Etapa 2 de 2',step:100})}${main(`<div class="card"><span class="tiny-label">CLIENTE</span><div class="strong" style="margin-top:8px">${esc(s.draft.name||'Cliente não informado')}</div><div class="caption">${esc(s.draft.document||'Documento não informado')} · ${esc(s.draft.phone||'WhatsApp não informado')}</div></div><div class="card"><span class="tiny-label">VEÍCULO</span><div class="row spread" style="margin-top:8px"><span>Valor</span><strong>${esc(s.draft.vehicle||'Não informado')}</strong></div><div class="caption">Aquisição: ${esc(s.draft.date||'Não informada')}</div></div><div class="alert amber">A criação nesta página é fictícia. O app real exige os campos e contratos do cadastro.</div>`)}${footer('Criar pedido fictício','create-order')}`,
    simulator:()=>`${header('Simular parcelas',{back:true})}${main(`<div class="alert blue">Consulta independente. Não inicia cobrança nem altera pedido.</div>${field('Valor para simular','sim',s.simDigits?'R$ '+(Number(s.simDigits)/100).toFixed(2).replace('.',','):'','R$ 0,00')}<h3 class="section-title">Condições ilustrativas</h3>${[1,2,3,6].map(n=>{const value=Number(s.simDigits||0);const total=value+(n>1?Math.round(value*.029):0);return `<div class="card row spread"><strong>${n}× ${fmt(Math.round(total/n))}</strong><span class="caption">Total ${fmt(total)}</span></div>`}).join('')}<p class="hint">As taxas são fictícias. No aplicativo, as condições devem vir da consulta de parcelas.</p>`)}${nav('simulator')}`,
    profile:()=>`${header('Perfil',{back:true})}${main(`<div class="card"><span class="tiny-label">CONCESSIONÁRIA</span><h3 style="margin:7px 0 3px">Auto Central</h3><div class="caption">00.000.000/0001-00 · Demonstração</div></div><div class="card"><span class="tiny-label">OPERADOR</span><div class="row spread" style="margin-top:8px"><strong>Ana Oliveira</strong><span class="chip paid">ATIVO</span></div></div><h3 class="section-title">Equipe</h3><div class="card"><div class="row spread"><span>Vendedores cadastrados</span><strong>3</strong></div></div><button class="secondary" data-action="login">Sair da demonstração</button>`)}${nav('profile')}`,
  };

  function field(label,id,value,placeholder,type='text'){return `<div class="field"><label for="field-${id}">${label}</label><input id="field-${id}" data-field="${id}" type="${type}" value="${esc(value)}" placeholder="${placeholder}" autocomplete="off"></div>`}
  function paymentOption(id,symbol,title,sub){return `<button type="button" class="payment-option" data-method="${id}"><span class="circle-icon">${symbol}</span><span class="grow"><strong>${title}</strong><small>${sub}</small></span><span class="chev">›</span></button>`}
  function filtered(){return s.orders.filter(o=>{const q=s.search.toLowerCase().trim();return !q||String(o.id).includes(q)||o.name.toLowerCase().includes(q)})}
  function renderOrderList(){
    if(s.screen!=='orders')return;
    const list=filtered();
    document.getElementById('order-list').innerHTML=list.length?list.map(o=>{
      const progress=o.total>0?Math.min(100,Math.max(0,Math.round(o.paid/o.total*100))):0;
      return `<button class="card clickable order-row" data-order="${o.id}"><div class="order-top"><span class="order-id">#${o.id}</span><span class="date">▣ ${esc(o.date.toUpperCase())}</span>${chip(o)}</div><div class="customer">${esc(o.name)}</div><div class="order-payment"><div class="payment-progress ${progress===100?'complete':''}" role="progressbar" aria-label="Pagamento do pedido ${o.id}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${progress}" aria-valuetext="${progress}% recebido"><i style="width:${progress}%"></i></div></div><div class="order-metrics"><div><span>TOTAL</span><strong class="money">${fmt(o.total)}</strong></div><div><span>↗ PAGO</span><strong class="money">${fmt(o.paid)}</strong></div><div><span>↘ ${balance(o)===0?'SALDO':'FALTA'}</span><strong class="money ${balance(o)>0?'due':'settled'}">${fmt(balance(o))}</strong></div></div></button>`;
    }).join(''):'<div class="card"><strong>Nenhum pedido encontrado</strong><p class="hint">Tente outra busca.</p></div>';
  }
  function render(){app.innerHTML=views[s.screen]();const info=screenInfo[s.screen];document.getElementById('stage-title').textContent=info[0];document.getElementById('note-title').textContent=info[1];document.getElementById('note-body').textContent=info[2];document.getElementById('note-tip').textContent=info[3];document.getElementById('screen-list').innerHTML=[['orders','Pedidos'],['detail','Detalhe'],['methods','Meios'],['amount','Valor'],['installments','Parcelas'],['review','Revisão'],['processing','Terminal'],['result','Resultado'],['new-order','Novo pedido'],['new-review','Revisar pedido'],['simulator','Simulador'],['profile','Perfil'],['login','Acesso']].map(([id,label])=>`<button data-screen="${id}" class="${s.screen===id?'active':''}">${label}</button>`).join('');document.getElementById('simulation').innerHTML=s.screen==='processing'?'<strong>Controle da demonstração</strong><button data-simulate="approved">Simular aprovação</button><button data-simulate="declined">Simular recusa</button><button data-simulate="unknown">Simular ausência de confirmação</button>':'';renderOrderList();if(s.toast){const n=document.createElement('div');n.className='toast';n.textContent=s.toast;app.appendChild(n);setTimeout(()=>n.remove(),2400);s.toast=null}}
  function go(screen){if(!views[screen])return;if(['detail','methods','amount','installments','review','processing','result'].includes(screen)&&!order())s.selected=s.orders[0].id;if(['amount','installments','review','processing','result'].includes(screen)&&!s.digits)s.digits=String(balance(order()));if(screen==='result'&&!s.result)s.result='unknown';s.screen=screen;render()}
  function back(){const map={orders:'login',detail:'orders',methods:'detail',amount:'methods',installments:'amount',review:s.method==='credito'?'installments':'amount',processing:'review',result:'detail','new-order':'orders','new-review':'new-order',simulator:'orders',profile:'orders',login:'orders'};go(map[s.screen]||'orders')}
  function validateAmount(){const err=document.getElementById('amount-error');if(!err)return;err.textContent=amount()>balance(order())?'Valor acima do saldo do pedido.':'';const button=app.querySelector('[data-action="amount-next"]');if(button)button.disabled=amount()<=0||amount()>balance(order())}
  function handle(action){switch(action){case 'back':back();break;case 'orders':go('orders');break;case 'toggle-search':s.showSearch=!s.showSearch;if(!s.showSearch)s.search='';render();break;case 'profile':go('profile');break;case 'new-order':go('new-order');break;case 'simulator':go('simulator');break;case 'detail':go('detail');break;case 'pay':s.method='credito';s.digits='';s.installments=1;s.result=null;go('methods');break;case 'copy-total':s.toast='Valor copiado apenas nesta demonstração.';render();break;case 'fill-balance':s.digits=String(balance(order()));document.getElementById('amount-display').textContent=fmt(amount());validateAmount();break;case 'amount-next':if(amount()<=0||amount()>balance(order()))return;s.installments=1;go(s.method==='credito'?'installments':'review');break;case 'review':go('review');break;case 'confirm':if(isManual()){s.result='approved';order().paid=Math.min(order().total,order().paid+amount());go('result')}else go('processing');break;case 'new-review':if(!s.draft.name.trim()||!s.draft.vehicle.trim()){s.toast='Informe nome e valor do veículo.';render();return}go('new-review');break;case 'create-order':{const raw=s.draft.vehicle.replace(/\D/g,'');const total=Math.max(0,Number(raw));const id=Math.max(...s.orders.map(o=>o.id))+1;s.orders.unshift({id,name:s.draft.name.trim(),date:'hoje',total,paid:0,photos:0});s.selected=id;s.detailDocumentsOpen=false;s.toast='Pedido fictício criado nesta demonstração.';go('detail');break}case 'login-submit':s.toast='Acesso simulado. Nenhum dado foi enviado.';go('orders');break;case 'login':go('login');break;case 'view-photos':s.detailDocumentsOpen=true;render();break;case 'take-photo':s.toast='Câmera indisponível no protótipo web.';render();break;default:break}}
  app.addEventListener('click',event=>{const target=event.target.closest('[data-action],[data-order],[data-method],[data-key],[data-installments]');if(!target)return;if(target.dataset.action){handle(target.dataset.action);return}if(target.dataset.order){s.selected=Number(target.dataset.order);s.detailDocumentsOpen=false;go('detail');return}if(target.dataset.method){s.method=target.dataset.method;s.digits='';go('amount');return}if(target.dataset.installments){s.installments=Number(target.dataset.installments);render();return}if(target.dataset.key){const k=target.dataset.key;if(k==='Limpar')s.digits='';else if(k==='⌫')s.digits=s.digits.slice(0,-1);else s.digits=(s.digits+k).replace(/^0+(?=\d)/,'').slice(0,9);document.getElementById('amount-display').textContent=fmt(amount());validateAmount()}});
  app.addEventListener('input',event=>{const id=event.target.dataset.field;if(!id)return;if(id==='search'){s.search=event.target.value;renderOrderList()}else if(id==='sim'){s.simDigits=event.target.value.replace(/\D/g,'');const pos=event.target.selectionStart;render();const input=app.querySelector('[data-field="sim"]');input.focus();input.setSelectionRange(Math.min(pos,input.value.length),Math.min(pos,input.value.length))}else if(id==='login-document')s.loginDocument=event.target.value;else if(id==='login-password')s.loginPassword=event.target.value;else s.draft[id]=event.target.value});
  document.getElementById('screen-list').addEventListener('click',event=>{const button=event.target.closest('[data-screen]');if(button)go(button.dataset.screen)});
  document.getElementById('simulation').addEventListener('click',event=>{const button=event.target.closest('[data-simulate]');if(!button)return;s.result=button.dataset.simulate;if(s.result==='approved')order().paid=Math.min(order().total,order().paid+amount());go('result')});
  document.getElementById('reset').addEventListener('click',()=>{s=fresh();render()});
  document.addEventListener('keydown',event=>{if(event.key==='Escape'){back()}});
  render();
})();
